spring.application.name=portfolio
# URL de conexion
spring.datasource.url=${PORTFOLIO_DB_URL}
# Usuario y contrasena
spring.datasource.username=${PORTFOLIO_DB_USER}
spring.datasource.password=${PORTFOLIO_DB_PASS}
# Driver JDBC
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${PORTFOLIO_MAIL_USER}
spring.mail.password=${PORTFOLIO_MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
